// =============================================================================
// build_opaque_bounds.mjs — precompute each solid prop's OPAQUE-PIXEL bounds from
// its PNG, so colliders can be derived from the VISIBLE silhouette (not the frame).
// Writes src/data/opaqueBounds.js (the SSOT read by BOTH the scene and verify.mjs).
//
// Minimal 8-bit RGBA (colorType 6, non-interlaced) PNG decoder using Node zlib —
// no external deps. Re-run after changing any solid prop art:  node scripts/build_opaque_bounds.mjs
// =============================================================================
import fs from 'node:fs';
import zlib from 'node:zlib';

// Parse the prop key→src map from assets.js as TEXT (not import) so this can regenerate even when
// src/data/opaqueBounds.js — which assets.js imports — does not yet exist (no circular dependency).
const assetsSrc = fs.readFileSync('src/data/assets.js', 'utf8');
const PROPS = {};
for (const m of assetsSrc.matchAll(/(prop_[a-z0-9_]+):\s*\{[^}]*?src:\s*'([^']+)'/g)) PROPS[m[1]] = { src: m[2] };

const ALPHA = 16; // alpha > this counts as opaque
const BASE_BAND_FRAC = 0.14, BASE_BAND_MAX = 16; // the ground-contact band (trunk / wall-foot)

function decodeRGBA(buf) {
  // verify PNG signature
  if (buf.readUInt32BE(0) !== 0x89504e47) throw new Error('not a PNG');
  let pos = 8, width = 0, height = 0, bitDepth = 0, colorType = 0, interlace = 0;
  const idat = [];
  while (pos < buf.length) {
    const len = buf.readUInt32BE(pos); const type = buf.toString('ascii', pos + 4, pos + 8);
    const data = buf.subarray(pos + 8, pos + 8 + len);
    if (type === 'IHDR') { width = data.readUInt32BE(0); height = data.readUInt32BE(4); bitDepth = data[8]; colorType = data[9]; interlace = data[12]; }
    else if (type === 'IDAT') idat.push(data);
    else if (type === 'IEND') break;
    pos += 12 + len;
  }
  if (bitDepth !== 8 || colorType !== 6 || interlace !== 0) throw new Error(`unsupported PNG (bd${bitDepth} ct${colorType} il${interlace})`);
  const raw = zlib.inflateSync(Buffer.concat(idat));
  const bpp = 4, stride = width * bpp;
  const out = Buffer.alloc(height * stride);
  const paeth = (a, b, c) => { const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c); return pa <= pb && pa <= pc ? a : pb <= pc ? b : c; };
  for (let y = 0; y < height; y++) {
    const ft = raw[y * (stride + 1)];
    const inRow = y * (stride + 1) + 1, outRow = y * stride, prevRow = outRow - stride;
    for (let x = 0; x < stride; x++) {
      const v = raw[inRow + x];
      const a = x >= bpp ? out[outRow + x - bpp] : 0;
      const b = y > 0 ? out[prevRow + x] : 0;
      const c = x >= bpp && y > 0 ? out[prevRow + x - bpp] : 0;
      let r;
      switch (ft) {
        case 0: r = v; break;
        case 1: r = v + a; break;
        case 2: r = v + b; break;
        case 3: r = v + ((a + b) >> 1); break;
        case 4: r = v + paeth(a, b, c); break;
        default: throw new Error('bad filter ' + ft);
      }
      out[outRow + x] = r & 0xff;
    }
  }
  return { width, height, data: out };
}

function opaqueBounds(img) {
  const { width: W, height: H, data } = img;
  let x0 = W, y0 = H, x1 = -1, y1 = -1;
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (data[(y * W + x) * 4 + 3] > ALPHA) { if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; }
  }
  if (x1 < 0) return null; // fully transparent
  // ground-contact band: opaque x-range in the bottom band of the silhouette (trunk / wall-foot)
  const bandH = Math.min(BASE_BAND_MAX, Math.max(2, Math.round((y1 - y0 + 1) * BASE_BAND_FRAC)));
  let bx0 = W, bx1 = -1;
  for (let y = y1 - bandH + 1; y <= y1; y++) for (let x = 0; x < W; x++) {
    if (data[(y * W + x) * 4 + 3] > ALPHA) { if (x < bx0) bx0 = x; if (x > bx1) bx1 = x; }
  }
  return { x0, y0, x1, y1, baseX0: bx0, baseX1: bx1 };
}

const out = {};
let ok = 0, skip = 0;
for (const [key, d] of Object.entries(PROPS)) {
  if (!d.src) { skip++; continue; }
  const file = 'public/' + d.src;
  try {
    const img = decodeRGBA(fs.readFileSync(file));
    const ob = opaqueBounds(img);
    if (!ob) { skip++; continue; }
    out[key] = ob;
    ok++;
  } catch (e) { console.error(`  ! ${key} (${d.src}): ${e.message}`); skip++; }
}

const body = `// AUTO-GENERATED by scripts/build_opaque_bounds.mjs — DO NOT EDIT BY HAND.
// Each solid prop's OPAQUE-PIXEL bounds (frame px, inclusive): the TRUE visible silhouette,
// ignoring transparent PNG padding. { x0,y0,x1,y1 } = opaque bbox; { baseX0,baseX1 } = opaque
// x-range in the ground-contact band (trunk / wall-foot). Read by assets.js solidBox + verify.mjs.
export const OPAQUE_BOUNDS = ${JSON.stringify(out, null, 0).replace(/\},/g, '},\n  ').replace('{', '{\n  ').replace(/\}$/, '\n}')};
`;
fs.writeFileSync('src/data/opaqueBounds.js', body);
console.log(`opaque-bounds: wrote ${ok} prop bounds (${skip} skipped) → src/data/opaqueBounds.js`);
