// Parse the bluecarrot16 [LPC] Terrains .tsx (corner-terrain format) into a compact
// runtime autotile map for the terrains Emberfall uses. Grass is the base; overlays
// (dirt/soil/gravel/sand) feather INTO grass via their corner-transition tiles.
import fs from 'node:fs';
const tsx = fs.readFileSync('asset-library/2d/tiles/lpc-terrains/terrain-v7.tsx', 'utf8');
// terrain index = order of <terrain ...> appearance
const names = [...tsx.matchAll(/<terrain name="([^"]+)" tile="(\d+)"/g)].map((m) => m[1]);
const idx = (n) => names.indexOf(n);
const GRASS = idx('Grass');
const OVERLAYS = { dirt: idx('Dirt_Tan'), road: idx('Dirt_Brown'), soil: idx('Soil'), gravel: idx('Gravel_1'), sand: idx('Sand'),
  // mountain/biome ground sets (Sundered Peaks + future regions) — already in the shipped atlas
  rock: idx('Rock_Gray'), snow: idx('Snow_1'), stone: idx('Stone_Tan'), ash: idx('Earth_Cracked'), lava: idx('Lava'),
  // FULL biome coverage so future regions (Coast/Marsh/Spire/Emberwood) have their ground ready.
  // Every overlay = a named terrain in the shipped atlas; corner-transitions into grass are captured
  // by setFor (a set with no grass-feather tiles comes out empty + is dropped below — flagged).
  dirt_dark: idx('Dirt_Dark'), dirt_roots: idx('Dirt_Roots'),
  grass_dark: idx('Grass_Dark'), grass_dead: idx('Grass_Dead'), grass_light: idx('Grass_Light'),
  mud: idx('Mud_Brown'), mudstone: idx('Mudstone_Gray'), mudstone_brown: idx('Mudstone_Brown'),
  rock_dark: idx('Rock_Dark'), rock_black: idx('Rock_Black'), rock_white: idx('Rock_White'),
  snow2: idx('Snow_2'), stone_white: idx('Stone_White'),
  ice: idx('Ice'), ice_melting: idx('Ice_Melting'),
  water: idx('Water'), water_deep: idx('Water_Deep'), water_green: idx('Water_Green'),
  water_shallows_sand: idx('Water_Shallows_Sand'), water_shallows_dirt: idx('Water_Shallows_Dirt'),
  hole: idx('Hole_Brown') };
// all <tile id="N" terrain="tl,tr,bl,br"/>
const tiles = [...tsx.matchAll(/<tile id="(\d+)" terrain="([^"]*)"\/>/g)].map((m) => ({ id: +m[1], c: m[2].split(',') }));
// for overlay k: tiles whose corners are all in {"", k}; key = which corners are k (tl,tr,bl,br)
function setFor(k) {
  const edges = {}; let full = null;
  for (const t of tiles) {
    if (t.c.length !== 4) continue;
    const isK = (c) => c !== '' && +c === k;
    if (!t.c.every((c) => c === '' || +c === k) || !t.c.some(isK)) continue;
    const key = t.c.map((c) => (isK(c) ? 1 : 0)).join('');
    if (key === '1111') { full = full ?? t.id; }
    else if (!(key in edges)) edges[key] = t.id;
  }
  return { full, edges };
}
// the full grass tile (all corners grass)
const grassFull = (tiles.find((t) => t.c.length === 4 && t.c.every((c) => +c === GRASS)) || {}).id;
const out = { cols: 32, grass: grassFull, sets: {} };
const dropped = [];
for (const [name, k] of Object.entries(OVERLAYS)) {
  if (k < 0) { dropped.push(`${name} (not in atlas)`); continue; }   // a name typo / missing terrain
  const s = setFor(k);
  if (s.full == null && Object.keys(s.edges).length === 0) { dropped.push(`${name} (no grass-feather tiles in atlas)`); continue; }
  out.sets[name] = s;
}
fs.writeFileSync('src/data/terrainTiles.js',
  '// AUTO-GENERATED by scripts/build_terrain_autotile.mjs from the [LPC] Terrains atlas\n' +
  '// (bluecarrot16 et al., CC-BY/CC-BY-SA/GPL — AI-safe). Corner-autotile maps: key = which\n' +
  '// of the 4 corners (tl,tr,bl,br) are the overlay terrain; value = the atlas tile index.\n' +
  'export const TERRAIN = ' + JSON.stringify(out, null, 1) + ';\n');
console.log('grass full tile:', grassFull, '| terrains:', names.length, '| wired sets:', Object.keys(out.sets).length);
for (const [n, s] of Object.entries(out.sets)) console.log(' ', n.padEnd(20), 'full', String(s.full).padStart(4), 'edge-patterns', Object.keys(s.edges).length);
if (dropped.length) console.log('DROPPED (flag — needs a non-grass base or its own tileset):', dropped.join(', '));
